apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-all-nodes
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-all
  template:
    metadata:
      labels:
        app: nginx-all
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
