# roles/kubernetes/tasks/worker.yml

- name: Wait for master join command to be available
  wait_for:
    timeout: 60

- name: Join the Kubernetes cluster
  command: "{{ hostvars[groups['master'][0]].join_command }} --ignore-preflight-errors=all"
  args:
    creates: /etc/kubernetes/kubelet.conf
