
# tasks file for common
- name: Install Docker
  become: true
  apt:
    name: docker.io
    state: present
    update_cache: true
  

- name: Install Docker SDK for Python (required by Ansible docker modules)
  apt:
    name: python3-docker
    state: present
- name: Install kubectl
  apt:
    name: kubectl
    state: present
    update_cache: true
- name: Install kubeadmin
  apt:
    name: kubeadm
    state: present
    update_cache: true 
- name: Install kubelet
  apt:
    name: kubelet
    state: present
    update_cache: true
- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: true
- name: Install python3-venv
  apt:
    name: python3-venv
    state: present
    update_cache: true
# - name: Install etcd
#   apt:
#     name: etcd
#     state: present
#     update_cache: true
# - name: Install apiserver
#   apt:
#     name: apiserver
#     state: present
#     update_cache: true
# - name: Install controller-manager
#   apt:
#     name: controller-manager
#     state: present
#     update_cache: true
# - name: Install scheduler
#   apt:
#     name: scheduler
#     state: present
#     update_cache: true
- name: Install cni-plugins
  apt:
    name: cni-plugins
    state: present
    update_cache: true
# - name: Install kube-proxy
#   apt:
#     name: kube-proxy
#     state: present
#     update_cache: true